[2023-04-19T12:42:41.127+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: age_check.age_check scheduled__2022-11-09T00:00:00+00:00 [queued]>
[2023-04-19T12:42:41.161+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: age_check.age_check scheduled__2022-11-09T00:00:00+00:00 [queued]>
[2023-04-19T12:42:41.164+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-04-19T12:42:41.166+0000] {taskinstance.py:1280} INFO - Starting attempt 3 of 4
[2023-04-19T12:42:41.168+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-04-19T12:42:41.210+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): age_check> on 2022-11-09 00:00:00+00:00
[2023-04-19T12:42:41.251+0000] {standard_task_runner.py:55} INFO - Started process 22980 to run task
[2023-04-19T12:42:41.273+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'age_check', 'age_check', 'scheduled__2022-11-09T00:00:00+00:00', '--job-id', '1208', '--raw', '--subdir', 'DAGS_FOLDER/age.py', '--cfg-path', '/tmp/tmpmw16jefr']
[2023-04-19T12:42:41.276+0000] {standard_task_runner.py:83} INFO - Job 1208: Subtask age_check
[2023-04-19T12:42:41.421+0000] {task_command.py:388} INFO - Running <TaskInstance: age_check.age_check scheduled__2022-11-09T00:00:00+00:00 [running]> on host fe34f61acbb3
[2023-04-19T12:42:41.538+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=age_check
AIRFLOW_CTX_TASK_ID=age_check
AIRFLOW_CTX_EXECUTION_DATE=2022-11-09T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-09T00:00:00+00:00
[2023-04-19T12:42:41.559+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/age.py", line 35, in age_check
    birth_year = int(Variable.get('birth_year'))
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable birth_year does not exist'
[2023-04-19T12:42:41.589+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=age_check, task_id=age_check, execution_date=20221109T000000, start_date=20230419T124241, end_date=20230419T124241
[2023-04-19T12:42:41.605+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 1208 for task age_check ('Variable birth_year does not exist'; 22980)
[2023-04-19T12:42:41.637+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-04-19T12:42:41.698+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-05-17T10:14:36.102+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: age_check.age_check scheduled__2022-11-09T00:00:00+00:00 [queued]>
[2023-05-17T10:14:36.115+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: age_check.age_check scheduled__2022-11-09T00:00:00+00:00 [queued]>
[2023-05-17T10:14:36.117+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-05-17T10:14:36.119+0000] {taskinstance.py:1280} INFO - Starting attempt 3 of 4
[2023-05-17T10:14:36.121+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-05-17T10:14:36.154+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): age_check> on 2022-11-09 00:00:00+00:00
[2023-05-17T10:14:36.160+0000] {standard_task_runner.py:55} INFO - Started process 5658 to run task
[2023-05-17T10:14:36.195+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'age_check', 'age_check', 'scheduled__2022-11-09T00:00:00+00:00', '--job-id', '768', '--raw', '--subdir', 'DAGS_FOLDER/age.py', '--cfg-path', '/tmp/tmp5f826gpn']
[2023-05-17T10:14:36.200+0000] {standard_task_runner.py:83} INFO - Job 768: Subtask age_check
[2023-05-17T10:14:36.300+0000] {task_command.py:388} INFO - Running <TaskInstance: age_check.age_check scheduled__2022-11-09T00:00:00+00:00 [running]> on host 242f95e3e8a8
[2023-05-17T10:14:36.369+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=age_check
AIRFLOW_CTX_TASK_ID=age_check
AIRFLOW_CTX_EXECUTION_DATE=2022-11-09T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-09T00:00:00+00:00
[2023-05-17T10:14:36.383+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/age.py", line 35, in age_check
    birth_year = int(Variable.get('birth_year'))
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable birth_year does not exist'
[2023-05-17T10:14:36.409+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=age_check, task_id=age_check, execution_date=20221109T000000, start_date=20230517T101436, end_date=20230517T101436
[2023-05-17T10:14:36.418+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 768 for task age_check ('Variable birth_year does not exist'; 5658)
[2023-05-17T10:14:36.469+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-05-17T10:14:36.498+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
