[2023-04-19T12:52:24.272+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: age_check.age_check scheduled__2023-04-04T00:00:00+00:00 [queued]>
[2023-04-19T12:52:24.412+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: age_check.age_check scheduled__2023-04-04T00:00:00+00:00 [queued]>
[2023-04-19T12:52:24.415+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-04-19T12:52:24.419+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 4
[2023-04-19T12:52:24.422+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-04-19T12:52:24.513+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): age_check> on 2023-04-04 00:00:00+00:00
[2023-04-19T12:52:24.559+0000] {standard_task_runner.py:55} INFO - Started process 25633 to run task
[2023-04-19T12:52:24.579+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'age_check', 'age_check', 'scheduled__2023-04-04T00:00:00+00:00', '--job-id', '2309', '--raw', '--subdir', 'DAGS_FOLDER/age.py', '--cfg-path', '/tmp/tmpjood02vx']
[2023-04-19T12:52:24.604+0000] {standard_task_runner.py:83} INFO - Job 2309: Subtask age_check
[2023-04-19T12:52:24.856+0000] {task_command.py:388} INFO - Running <TaskInstance: age_check.age_check scheduled__2023-04-04T00:00:00+00:00 [running]> on host fe34f61acbb3
[2023-04-19T12:52:25.173+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=age_check
AIRFLOW_CTX_TASK_ID=age_check
AIRFLOW_CTX_EXECUTION_DATE=2023-04-04T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-04T00:00:00+00:00
[2023-04-19T12:52:25.231+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/age.py", line 35, in age_check
    birth_year = int(Variable.get('birth_year'))
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable birth_year does not exist'
[2023-04-19T12:52:25.255+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=age_check, task_id=age_check, execution_date=20230404T000000, start_date=20230419T125224, end_date=20230419T125225
[2023-04-19T12:52:25.314+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 2309 for task age_check ('Variable birth_year does not exist'; 25633)
[2023-04-19T12:52:25.400+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-04-19T12:52:25.536+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-05-20T21:49:48.136+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: age_check.age_check scheduled__2023-04-04T00:00:00+00:00 [queued]>
[2023-05-20T21:49:48.166+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: age_check.age_check scheduled__2023-04-04T00:00:00+00:00 [queued]>
[2023-05-20T21:49:48.169+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-05-20T21:49:48.179+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 4
[2023-05-20T21:49:48.180+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-05-20T21:49:48.231+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): age_check> on 2023-04-04 00:00:00+00:00
[2023-05-20T21:49:48.246+0000] {standard_task_runner.py:55} INFO - Started process 2146 to run task
[2023-05-20T21:49:48.271+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'age_check', 'age_check', 'scheduled__2023-04-04T00:00:00+00:00', '--job-id', '1759', '--raw', '--subdir', 'DAGS_FOLDER/age.py', '--cfg-path', '/tmp/tmpreetizuj']
[2023-05-20T21:49:48.281+0000] {standard_task_runner.py:83} INFO - Job 1759: Subtask age_check
[2023-05-20T21:49:48.524+0000] {task_command.py:388} INFO - Running <TaskInstance: age_check.age_check scheduled__2023-04-04T00:00:00+00:00 [running]> on host 242f95e3e8a8
[2023-05-20T21:49:48.719+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=age_check
AIRFLOW_CTX_TASK_ID=age_check
AIRFLOW_CTX_EXECUTION_DATE=2023-04-04T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-04T00:00:00+00:00
[2023-05-20T21:49:48.743+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/age.py", line 35, in age_check
    birth_year = int(Variable.get('birth_year'))
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable birth_year does not exist'
[2023-05-20T21:49:48.785+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=age_check, task_id=age_check, execution_date=20230404T000000, start_date=20230520T214948, end_date=20230520T214948
[2023-05-20T21:49:48.805+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 1759 for task age_check ('Variable birth_year does not exist'; 2146)
[2023-05-20T21:49:48.892+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-05-20T21:49:48.985+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
