[2023-04-19T12:53:05.114+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: age_check.age_check scheduled__2023-04-04T00:00:00+00:00 [queued]>
[2023-04-19T12:53:05.224+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: age_check.age_check scheduled__2023-04-04T00:00:00+00:00 [queued]>
[2023-04-19T12:53:05.229+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-04-19T12:53:05.231+0000] {taskinstance.py:1280} INFO - Starting attempt 4 of 4
[2023-04-19T12:53:05.236+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-04-19T12:53:05.356+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): age_check> on 2023-04-04 00:00:00+00:00
[2023-04-19T12:53:05.442+0000] {standard_task_runner.py:55} INFO - Started process 25880 to run task
[2023-04-19T12:53:05.469+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'age_check', 'age_check', 'scheduled__2023-04-04T00:00:00+00:00', '--job-id', '2413', '--raw', '--subdir', 'DAGS_FOLDER/age.py', '--cfg-path', '/tmp/tmpiij5njca']
[2023-04-19T12:53:05.501+0000] {standard_task_runner.py:83} INFO - Job 2413: Subtask age_check
[2023-04-19T12:53:05.764+0000] {task_command.py:388} INFO - Running <TaskInstance: age_check.age_check scheduled__2023-04-04T00:00:00+00:00 [running]> on host fe34f61acbb3
[2023-04-19T12:53:06.107+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=age_check
AIRFLOW_CTX_TASK_ID=age_check
AIRFLOW_CTX_EXECUTION_DATE=2023-04-04T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-04T00:00:00+00:00
[2023-04-19T12:53:06.132+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/age.py", line 35, in age_check
    birth_year = int(Variable.get('birth_year'))
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable birth_year does not exist'
[2023-04-19T12:53:06.166+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=age_check, task_id=age_check, execution_date=20230404T000000, start_date=20230419T125305, end_date=20230419T125306
[2023-04-19T12:53:06.218+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 2413 for task age_check ('Variable birth_year does not exist'; 25880)
[2023-04-19T12:53:06.371+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-04-19T12:53:06.882+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-05-20T21:50:22.460+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: age_check.age_check scheduled__2023-04-04T00:00:00+00:00 [queued]>
[2023-05-20T21:50:22.473+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: age_check.age_check scheduled__2023-04-04T00:00:00+00:00 [queued]>
[2023-05-20T21:50:22.474+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-05-20T21:50:22.475+0000] {taskinstance.py:1280} INFO - Starting attempt 4 of 4
[2023-05-20T21:50:22.476+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-05-20T21:50:22.489+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): age_check> on 2023-04-04 00:00:00+00:00
[2023-05-20T21:50:22.494+0000] {standard_task_runner.py:55} INFO - Started process 2284 to run task
[2023-05-20T21:50:22.504+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'age_check', 'age_check', 'scheduled__2023-04-04T00:00:00+00:00', '--job-id', '1817', '--raw', '--subdir', 'DAGS_FOLDER/age.py', '--cfg-path', '/tmp/tmpos1t9c36']
[2023-05-20T21:50:22.510+0000] {standard_task_runner.py:83} INFO - Job 1817: Subtask age_check
[2023-05-20T21:50:22.592+0000] {task_command.py:388} INFO - Running <TaskInstance: age_check.age_check scheduled__2023-04-04T00:00:00+00:00 [running]> on host 242f95e3e8a8
[2023-05-20T21:50:22.665+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=age_check
AIRFLOW_CTX_TASK_ID=age_check
AIRFLOW_CTX_EXECUTION_DATE=2023-04-04T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-04T00:00:00+00:00
[2023-05-20T21:50:22.675+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/age.py", line 35, in age_check
    birth_year = int(Variable.get('birth_year'))
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable birth_year does not exist'
[2023-05-20T21:50:22.685+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=age_check, task_id=age_check, execution_date=20230404T000000, start_date=20230520T215022, end_date=20230520T215022
[2023-05-20T21:50:22.694+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 1817 for task age_check ('Variable birth_year does not exist'; 2284)
[2023-05-20T21:50:22.715+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-05-20T21:50:22.743+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
