[2023-04-19T12:43:53.252+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: age_check.age_check scheduled__2022-11-19T00:00:00+00:00 [queued]>
[2023-04-19T12:43:53.276+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: age_check.age_check scheduled__2022-11-19T00:00:00+00:00 [queued]>
[2023-04-19T12:43:53.283+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-04-19T12:43:53.284+0000] {taskinstance.py:1280} INFO - Starting attempt 4 of 4
[2023-04-19T12:43:53.287+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-04-19T12:43:53.323+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): age_check> on 2022-11-19 00:00:00+00:00
[2023-04-19T12:43:53.334+0000] {standard_task_runner.py:55} INFO - Started process 23288 to run task
[2023-04-19T12:43:53.352+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'age_check', 'age_check', 'scheduled__2022-11-19T00:00:00+00:00', '--job-id', '1329', '--raw', '--subdir', 'DAGS_FOLDER/age.py', '--cfg-path', '/tmp/tmpj1woao4r']
[2023-04-19T12:43:53.358+0000] {standard_task_runner.py:83} INFO - Job 1329: Subtask age_check
[2023-04-19T12:43:53.557+0000] {task_command.py:388} INFO - Running <TaskInstance: age_check.age_check scheduled__2022-11-19T00:00:00+00:00 [running]> on host fe34f61acbb3
[2023-04-19T12:43:53.677+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=age_check
AIRFLOW_CTX_TASK_ID=age_check
AIRFLOW_CTX_EXECUTION_DATE=2022-11-19T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-19T00:00:00+00:00
[2023-04-19T12:43:53.697+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/age.py", line 35, in age_check
    birth_year = int(Variable.get('birth_year'))
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable birth_year does not exist'
[2023-04-19T12:43:53.724+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=age_check, task_id=age_check, execution_date=20221119T000000, start_date=20230419T124353, end_date=20230419T124353
[2023-04-19T12:43:53.739+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 1329 for task age_check ('Variable birth_year does not exist'; 23288)
[2023-04-19T12:43:53.799+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-04-19T12:43:53.821+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-05-17T10:48:20.865+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: age_check.age_check scheduled__2022-11-19T00:00:00+00:00 [queued]>
[2023-05-17T10:48:20.873+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: age_check.age_check scheduled__2022-11-19T00:00:00+00:00 [queued]>
[2023-05-17T10:48:20.877+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-05-17T10:48:20.881+0000] {taskinstance.py:1280} INFO - Starting attempt 4 of 4
[2023-05-17T10:48:20.883+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-05-17T10:48:20.898+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): age_check> on 2022-11-19 00:00:00+00:00
[2023-05-17T10:48:20.906+0000] {standard_task_runner.py:55} INFO - Started process 5964 to run task
[2023-05-17T10:48:20.910+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'age_check', 'age_check', 'scheduled__2022-11-19T00:00:00+00:00', '--job-id', '892', '--raw', '--subdir', 'DAGS_FOLDER/age.py', '--cfg-path', '/tmp/tmp1129fs5n']
[2023-05-17T10:48:20.914+0000] {standard_task_runner.py:83} INFO - Job 892: Subtask age_check
[2023-05-17T10:48:21.012+0000] {task_command.py:388} INFO - Running <TaskInstance: age_check.age_check scheduled__2022-11-19T00:00:00+00:00 [running]> on host 242f95e3e8a8
[2023-05-17T10:48:21.088+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=age_check
AIRFLOW_CTX_TASK_ID=age_check
AIRFLOW_CTX_EXECUTION_DATE=2022-11-19T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-19T00:00:00+00:00
[2023-05-17T10:48:21.100+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/age.py", line 35, in age_check
    birth_year = int(Variable.get('birth_year'))
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable birth_year does not exist'
[2023-05-17T10:48:21.115+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=age_check, task_id=age_check, execution_date=20221119T000000, start_date=20230517T104820, end_date=20230517T104821
[2023-05-17T10:48:21.127+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 892 for task age_check ('Variable birth_year does not exist'; 5964)
[2023-05-17T10:48:21.164+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-05-17T10:48:21.189+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
