[2023-04-19T12:51:21.259+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: age_check.age_check scheduled__2023-03-21T00:00:00+00:00 [queued]>
[2023-04-19T12:51:21.271+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: age_check.age_check scheduled__2023-03-21T00:00:00+00:00 [queued]>
[2023-04-19T12:51:21.273+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-04-19T12:51:21.274+0000] {taskinstance.py:1280} INFO - Starting attempt 2 of 4
[2023-04-19T12:51:21.277+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-04-19T12:51:21.311+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): age_check> on 2023-03-21 00:00:00+00:00
[2023-04-19T12:51:21.323+0000] {standard_task_runner.py:55} INFO - Started process 25302 to run task
[2023-04-19T12:51:21.328+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'age_check', 'age_check', 'scheduled__2023-03-21T00:00:00+00:00', '--job-id', '2162', '--raw', '--subdir', 'DAGS_FOLDER/age.py', '--cfg-path', '/tmp/tmp7fquznaq']
[2023-04-19T12:51:21.330+0000] {standard_task_runner.py:83} INFO - Job 2162: Subtask age_check
[2023-04-19T12:51:21.454+0000] {task_command.py:388} INFO - Running <TaskInstance: age_check.age_check scheduled__2023-03-21T00:00:00+00:00 [running]> on host fe34f61acbb3
[2023-04-19T12:51:21.539+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=age_check
AIRFLOW_CTX_TASK_ID=age_check
AIRFLOW_CTX_EXECUTION_DATE=2023-03-21T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-21T00:00:00+00:00
[2023-04-19T12:51:21.548+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/age.py", line 35, in age_check
    birth_year = int(Variable.get('birth_year'))
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable birth_year does not exist'
[2023-04-19T12:51:21.563+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=age_check, task_id=age_check, execution_date=20230321T000000, start_date=20230419T125121, end_date=20230419T125121
[2023-04-19T12:51:21.574+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 2162 for task age_check ('Variable birth_year does not exist'; 25302)
[2023-04-19T12:51:21.587+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-04-19T12:51:21.616+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-05-20T21:49:09.267+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: age_check.age_check scheduled__2023-03-21T00:00:00+00:00 [queued]>
[2023-05-20T21:49:09.281+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: age_check.age_check scheduled__2023-03-21T00:00:00+00:00 [queued]>
[2023-05-20T21:49:09.282+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-05-20T21:49:09.283+0000] {taskinstance.py:1280} INFO - Starting attempt 2 of 4
[2023-05-20T21:49:09.293+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-05-20T21:49:09.322+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): age_check> on 2023-03-21 00:00:00+00:00
[2023-05-20T21:49:09.328+0000] {standard_task_runner.py:55} INFO - Started process 1955 to run task
[2023-05-20T21:49:09.341+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'age_check', 'age_check', 'scheduled__2023-03-21T00:00:00+00:00', '--job-id', '1683', '--raw', '--subdir', 'DAGS_FOLDER/age.py', '--cfg-path', '/tmp/tmpoq32qqnx']
[2023-05-20T21:49:09.345+0000] {standard_task_runner.py:83} INFO - Job 1683: Subtask age_check
[2023-05-20T21:49:09.531+0000] {task_command.py:388} INFO - Running <TaskInstance: age_check.age_check scheduled__2023-03-21T00:00:00+00:00 [running]> on host 242f95e3e8a8
[2023-05-20T21:49:09.638+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=age_check
AIRFLOW_CTX_TASK_ID=age_check
AIRFLOW_CTX_EXECUTION_DATE=2023-03-21T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-21T00:00:00+00:00
[2023-05-20T21:49:09.655+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/age.py", line 35, in age_check
    birth_year = int(Variable.get('birth_year'))
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable birth_year does not exist'
[2023-05-20T21:49:09.675+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=age_check, task_id=age_check, execution_date=20230321T000000, start_date=20230520T214909, end_date=20230520T214909
[2023-05-20T21:49:09.702+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 1683 for task age_check ('Variable birth_year does not exist'; 1955)
[2023-05-20T21:49:09.759+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-05-20T21:49:09.818+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
