[2023-04-19T12:50:31.404+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: age_check.age_check scheduled__2023-03-04T00:00:00+00:00 [queued]>
[2023-04-19T12:50:31.451+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: age_check.age_check scheduled__2023-03-04T00:00:00+00:00 [queued]>
[2023-04-19T12:50:31.455+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-04-19T12:50:31.456+0000] {taskinstance.py:1280} INFO - Starting attempt 4 of 4
[2023-04-19T12:50:31.458+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-04-19T12:50:31.513+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): age_check> on 2023-03-04 00:00:00+00:00
[2023-04-19T12:50:31.530+0000] {standard_task_runner.py:55} INFO - Started process 25037 to run task
[2023-04-19T12:50:31.545+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'age_check', 'age_check', 'scheduled__2023-03-04T00:00:00+00:00', '--job-id', '2047', '--raw', '--subdir', 'DAGS_FOLDER/age.py', '--cfg-path', '/tmp/tmpb32auo2b']
[2023-04-19T12:50:31.558+0000] {standard_task_runner.py:83} INFO - Job 2047: Subtask age_check
[2023-04-19T12:50:31.760+0000] {task_command.py:388} INFO - Running <TaskInstance: age_check.age_check scheduled__2023-03-04T00:00:00+00:00 [running]> on host fe34f61acbb3
[2023-04-19T12:50:31.961+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=age_check
AIRFLOW_CTX_TASK_ID=age_check
AIRFLOW_CTX_EXECUTION_DATE=2023-03-04T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-04T00:00:00+00:00
[2023-04-19T12:50:31.974+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/age.py", line 35, in age_check
    birth_year = int(Variable.get('birth_year'))
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable birth_year does not exist'
[2023-04-19T12:50:32.030+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=age_check, task_id=age_check, execution_date=20230304T000000, start_date=20230419T125031, end_date=20230419T125032
[2023-04-19T12:50:32.044+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 2047 for task age_check ('Variable birth_year does not exist'; 25037)
[2023-04-19T12:50:32.134+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-04-19T12:50:32.183+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-05-20T21:48:31.975+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: age_check.age_check scheduled__2023-03-04T00:00:00+00:00 [queued]>
[2023-05-20T21:48:32.068+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: age_check.age_check scheduled__2023-03-04T00:00:00+00:00 [queued]>
[2023-05-20T21:48:32.073+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-05-20T21:48:32.074+0000] {taskinstance.py:1280} INFO - Starting attempt 4 of 4
[2023-05-20T21:48:32.074+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-05-20T21:48:32.192+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): age_check> on 2023-03-04 00:00:00+00:00
[2023-05-20T21:48:32.208+0000] {standard_task_runner.py:55} INFO - Started process 1748 to run task
[2023-05-20T21:48:32.278+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'age_check', 'age_check', 'scheduled__2023-03-04T00:00:00+00:00', '--job-id', '1593', '--raw', '--subdir', 'DAGS_FOLDER/age.py', '--cfg-path', '/tmp/tmp8rn6ihl_']
[2023-05-20T21:48:32.295+0000] {standard_task_runner.py:83} INFO - Job 1593: Subtask age_check
[2023-05-20T21:48:32.750+0000] {task_command.py:388} INFO - Running <TaskInstance: age_check.age_check scheduled__2023-03-04T00:00:00+00:00 [running]> on host 242f95e3e8a8
[2023-05-20T21:48:33.107+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=age_check
AIRFLOW_CTX_TASK_ID=age_check
AIRFLOW_CTX_EXECUTION_DATE=2023-03-04T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-04T00:00:00+00:00
[2023-05-20T21:48:33.162+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/age.py", line 35, in age_check
    birth_year = int(Variable.get('birth_year'))
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable birth_year does not exist'
[2023-05-20T21:48:33.224+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=age_check, task_id=age_check, execution_date=20230304T000000, start_date=20230520T214831, end_date=20230520T214833
[2023-05-20T21:48:33.278+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 1593 for task age_check ('Variable birth_year does not exist'; 1748)
[2023-05-20T21:48:33.370+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-05-20T21:48:33.461+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
