[2023-04-19T12:45:49.635+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: age_check.age_check scheduled__2022-12-27T00:00:00+00:00 [queued]>
[2023-04-19T12:45:49.669+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: age_check.age_check scheduled__2022-12-27T00:00:00+00:00 [queued]>
[2023-04-19T12:45:49.672+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-04-19T12:45:49.674+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 4
[2023-04-19T12:45:49.676+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-04-19T12:45:49.763+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): age_check> on 2022-12-27 00:00:00+00:00
[2023-04-19T12:45:49.837+0000] {standard_task_runner.py:55} INFO - Started process 23766 to run task
[2023-04-19T12:45:49.895+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'age_check', 'age_check', 'scheduled__2022-12-27T00:00:00+00:00', '--job-id', '1520', '--raw', '--subdir', 'DAGS_FOLDER/age.py', '--cfg-path', '/tmp/tmp8wrwq52y']
[2023-04-19T12:45:49.904+0000] {standard_task_runner.py:83} INFO - Job 1520: Subtask age_check
[2023-04-19T12:45:50.795+0000] {task_command.py:388} INFO - Running <TaskInstance: age_check.age_check scheduled__2022-12-27T00:00:00+00:00 [running]> on host fe34f61acbb3
[2023-04-19T12:45:51.495+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=age_check
AIRFLOW_CTX_TASK_ID=age_check
AIRFLOW_CTX_EXECUTION_DATE=2022-12-27T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-27T00:00:00+00:00
[2023-04-19T12:45:51.590+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/age.py", line 35, in age_check
    birth_year = int(Variable.get('birth_year'))
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable birth_year does not exist'
[2023-04-19T12:45:51.705+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=age_check, task_id=age_check, execution_date=20221227T000000, start_date=20230419T124549, end_date=20230419T124551
[2023-04-19T12:45:51.805+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 1520 for task age_check ('Variable birth_year does not exist'; 23766)
[2023-04-19T12:45:51.954+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-04-19T12:45:52.310+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-05-20T20:57:00.771+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: age_check.age_check scheduled__2022-12-27T00:00:00+00:00 [queued]>
[2023-05-20T20:57:00.825+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: age_check.age_check scheduled__2022-12-27T00:00:00+00:00 [queued]>
[2023-05-20T20:57:00.830+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-05-20T20:57:00.831+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 4
[2023-05-20T20:57:00.834+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-05-20T20:57:00.894+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): age_check> on 2022-12-27 00:00:00+00:00
[2023-05-20T20:57:00.923+0000] {standard_task_runner.py:55} INFO - Started process 487 to run task
[2023-05-20T20:57:00.936+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'age_check', 'age_check', 'scheduled__2022-12-27T00:00:00+00:00', '--job-id', '1084', '--raw', '--subdir', 'DAGS_FOLDER/age.py', '--cfg-path', '/tmp/tmpvahln1bt']
[2023-05-20T20:57:00.943+0000] {standard_task_runner.py:83} INFO - Job 1084: Subtask age_check
[2023-05-20T20:57:01.141+0000] {task_command.py:388} INFO - Running <TaskInstance: age_check.age_check scheduled__2022-12-27T00:00:00+00:00 [running]> on host 242f95e3e8a8
[2023-05-20T20:57:01.294+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=age_check
AIRFLOW_CTX_TASK_ID=age_check
AIRFLOW_CTX_EXECUTION_DATE=2022-12-27T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-27T00:00:00+00:00
[2023-05-20T20:57:01.315+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/age.py", line 35, in age_check
    birth_year = int(Variable.get('birth_year'))
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable birth_year does not exist'
[2023-05-20T20:57:01.361+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=age_check, task_id=age_check, execution_date=20221227T000000, start_date=20230520T205700, end_date=20230520T205701
[2023-05-20T20:57:01.375+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 1084 for task age_check ('Variable birth_year does not exist'; 487)
[2023-05-20T20:57:01.428+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-05-20T20:57:01.463+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
