[2023-04-19T12:44:56.173+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: age_check.age_check scheduled__2022-12-17T00:00:00+00:00 [queued]>
[2023-04-19T12:44:56.210+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: age_check.age_check scheduled__2022-12-17T00:00:00+00:00 [queued]>
[2023-04-19T12:44:56.214+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-04-19T12:44:56.217+0000] {taskinstance.py:1280} INFO - Starting attempt 3 of 4
[2023-04-19T12:44:56.220+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-04-19T12:44:56.265+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): age_check> on 2022-12-17 00:00:00+00:00
[2023-04-19T12:44:56.272+0000] {standard_task_runner.py:55} INFO - Started process 23560 to run task
[2023-04-19T12:44:56.307+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'age_check', 'age_check', 'scheduled__2022-12-17T00:00:00+00:00', '--job-id', '1440', '--raw', '--subdir', 'DAGS_FOLDER/age.py', '--cfg-path', '/tmp/tmp6whvivpq']
[2023-04-19T12:44:56.309+0000] {standard_task_runner.py:83} INFO - Job 1440: Subtask age_check
[2023-04-19T12:44:56.524+0000] {task_command.py:388} INFO - Running <TaskInstance: age_check.age_check scheduled__2022-12-17T00:00:00+00:00 [running]> on host fe34f61acbb3
[2023-04-19T12:44:56.821+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=age_check
AIRFLOW_CTX_TASK_ID=age_check
AIRFLOW_CTX_EXECUTION_DATE=2022-12-17T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-17T00:00:00+00:00
[2023-04-19T12:44:56.866+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/age.py", line 35, in age_check
    birth_year = int(Variable.get('birth_year'))
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable birth_year does not exist'
[2023-04-19T12:44:56.954+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=age_check, task_id=age_check, execution_date=20221217T000000, start_date=20230419T124456, end_date=20230419T124456
[2023-04-19T12:44:56.973+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 1440 for task age_check ('Variable birth_year does not exist'; 23560)
[2023-04-19T12:44:57.033+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-04-19T12:44:57.254+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-05-20T20:56:34.903+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: age_check.age_check scheduled__2022-12-17T00:00:00+00:00 [queued]>
[2023-05-20T20:56:34.918+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: age_check.age_check scheduled__2022-12-17T00:00:00+00:00 [queued]>
[2023-05-20T20:56:34.919+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-05-20T20:56:34.921+0000] {taskinstance.py:1280} INFO - Starting attempt 3 of 4
[2023-05-20T20:56:34.922+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-05-20T20:56:34.940+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): age_check> on 2022-12-17 00:00:00+00:00
[2023-05-20T20:56:34.953+0000] {standard_task_runner.py:55} INFO - Started process 342 to run task
[2023-05-20T20:56:34.961+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'age_check', 'age_check', 'scheduled__2022-12-17T00:00:00+00:00', '--job-id', '1025', '--raw', '--subdir', 'DAGS_FOLDER/age.py', '--cfg-path', '/tmp/tmpky3jd7_8']
[2023-05-20T20:56:34.970+0000] {standard_task_runner.py:83} INFO - Job 1025: Subtask age_check
[2023-05-20T20:56:35.091+0000] {task_command.py:388} INFO - Running <TaskInstance: age_check.age_check scheduled__2022-12-17T00:00:00+00:00 [running]> on host 242f95e3e8a8
[2023-05-20T20:56:35.173+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=age_check
AIRFLOW_CTX_TASK_ID=age_check
AIRFLOW_CTX_EXECUTION_DATE=2022-12-17T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-17T00:00:00+00:00
[2023-05-20T20:56:35.182+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/age.py", line 35, in age_check
    birth_year = int(Variable.get('birth_year'))
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable birth_year does not exist'
[2023-05-20T20:56:35.194+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=age_check, task_id=age_check, execution_date=20221217T000000, start_date=20230520T205634, end_date=20230520T205635
[2023-05-20T20:56:35.206+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 1025 for task age_check ('Variable birth_year does not exist'; 342)
[2023-05-20T20:56:35.221+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-05-20T20:56:35.244+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
