[2023-04-24T02:30:35.368+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: age_check.age_check scheduled__2023-04-23T00:00:00+00:00 [queued]>
[2023-04-24T02:30:35.412+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: age_check.age_check scheduled__2023-04-23T00:00:00+00:00 [queued]>
[2023-04-24T02:30:35.414+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-04-24T02:30:35.415+0000] {taskinstance.py:1280} INFO - Starting attempt 4 of 4
[2023-04-24T02:30:35.417+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-04-24T02:30:35.498+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): age_check> on 2023-04-23 00:00:00+00:00
[2023-04-24T02:30:35.798+0000] {standard_task_runner.py:55} INFO - Started process 2549 to run task
[2023-04-24T02:30:35.832+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'age_check', 'age_check', 'scheduled__2023-04-23T00:00:00+00:00', '--job-id', '4523', '--raw', '--subdir', 'DAGS_FOLDER/age.py', '--cfg-path', '/tmp/tmphdei7g1r']
[2023-04-24T02:30:35.839+0000] {standard_task_runner.py:83} INFO - Job 4523: Subtask age_check
[2023-04-24T02:30:36.281+0000] {task_command.py:388} INFO - Running <TaskInstance: age_check.age_check scheduled__2023-04-23T00:00:00+00:00 [running]> on host fe34f61acbb3
[2023-04-24T02:30:36.531+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=age_check
AIRFLOW_CTX_TASK_ID=age_check
AIRFLOW_CTX_EXECUTION_DATE=2023-04-23T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-23T00:00:00+00:00
[2023-04-24T02:30:36.563+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/age.py", line 35, in age_check
    birth_year = int(Variable.get('birth_year'))
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable birth_year does not exist'
[2023-04-24T02:30:36.603+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=age_check, task_id=age_check, execution_date=20230423T000000, start_date=20230424T023035, end_date=20230424T023036
[2023-04-24T02:30:36.663+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 4523 for task age_check ('Variable birth_year does not exist'; 2549)
[2023-04-24T02:30:36.744+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-04-24T02:30:36.843+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-05-20T21:51:21.442+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: age_check.age_check scheduled__2023-04-23T00:00:00+00:00 [queued]>
[2023-05-20T21:51:21.470+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: age_check.age_check scheduled__2023-04-23T00:00:00+00:00 [queued]>
[2023-05-20T21:51:21.471+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-05-20T21:51:21.473+0000] {taskinstance.py:1280} INFO - Starting attempt 4 of 4
[2023-05-20T21:51:21.473+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-05-20T21:51:21.496+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): age_check> on 2023-04-23 00:00:00+00:00
[2023-05-20T21:51:21.517+0000] {standard_task_runner.py:55} INFO - Started process 2569 to run task
[2023-05-20T21:51:21.527+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'age_check', 'age_check', 'scheduled__2023-04-23T00:00:00+00:00', '--job-id', '1931', '--raw', '--subdir', 'DAGS_FOLDER/age.py', '--cfg-path', '/tmp/tmp_t4zk_9_']
[2023-05-20T21:51:21.538+0000] {standard_task_runner.py:83} INFO - Job 1931: Subtask age_check
[2023-05-20T21:51:21.650+0000] {task_command.py:388} INFO - Running <TaskInstance: age_check.age_check scheduled__2023-04-23T00:00:00+00:00 [running]> on host 242f95e3e8a8
[2023-05-20T21:51:21.804+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=age_check
AIRFLOW_CTX_TASK_ID=age_check
AIRFLOW_CTX_EXECUTION_DATE=2023-04-23T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-23T00:00:00+00:00
[2023-05-20T21:51:21.838+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/age.py", line 35, in age_check
    birth_year = int(Variable.get('birth_year'))
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable birth_year does not exist'
[2023-05-20T21:51:21.851+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=age_check, task_id=age_check, execution_date=20230423T000000, start_date=20230520T215121, end_date=20230520T215121
[2023-05-20T21:51:21.863+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 1931 for task age_check ('Variable birth_year does not exist'; 2569)
[2023-05-20T21:51:21.909+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-05-20T21:51:21.953+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
