[2023-12-17T15:31:51.780+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: read_s3_data.read_s3_data scheduled__2022-10-20T00:00:00+00:00 [queued]>
[2023-12-17T15:31:51.906+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: read_s3_data.read_s3_data scheduled__2022-10-20T00:00:00+00:00 [queued]>
[2023-12-17T15:31:51.910+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 4
[2023-12-17T15:31:52.183+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): read_s3_data> on 2022-10-20 00:00:00+00:00
[2023-12-17T15:31:52.353+0000] {standard_task_runner.py:57} INFO - Started process 27115 to run task
[2023-12-17T15:31:52.480+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'read_s3_data', 'read_s3_data', 'scheduled__2022-10-20T00:00:00+00:00', '--job-id', '6612', '--raw', '--subdir', 'DAGS_FOLDER/read.py', '--cfg-path', '/tmp/tmpd_zmfk5j']
[2023-12-17T15:31:52.518+0000] {standard_task_runner.py:85} INFO - Job 6612: Subtask read_s3_data
[2023-12-17T15:31:53.530+0000] {task_command.py:415} INFO - Running <TaskInstance: read_s3_data.read_s3_data scheduled__2022-10-20T00:00:00+00:00 [running]> on host 533efb53d454
[2023-12-17T15:31:54.647+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='read_s3_data' AIRFLOW_CTX_TASK_ID='read_s3_data' AIRFLOW_CTX_EXECUTION_DATE='2022-10-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-10-20T00:00:00+00:00'
[2023-12-17T15:31:54.666+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: generic_s3_clients() missing 2 required positional arguments: 'ACCESS_KEY' and 'SECRET_KEY'
[2023-12-17T15:31:54.727+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=read_s3_data, task_id=read_s3_data, execution_date=20221020T000000, start_date=20231217T153151, end_date=20231217T153154
[2023-12-17T15:31:54.755+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 6612 for task read_s3_data (generic_s3_clients() missing 2 required positional arguments: 'ACCESS_KEY' and 'SECRET_KEY'; 27115)
[2023-12-17T15:31:55.040+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-17T15:31:56.159+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-12-24T17:06:49.496+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: read_s3_data.read_s3_data scheduled__2022-10-20T00:00:00+00:00 [queued]>
[2023-12-24T17:06:49.532+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: read_s3_data.read_s3_data scheduled__2022-10-20T00:00:00+00:00 [queued]>
[2023-12-24T17:06:49.536+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 4
[2023-12-24T17:06:49.617+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): read_s3_data> on 2022-10-20 00:00:00+00:00
[2023-12-24T17:06:49.655+0000] {standard_task_runner.py:57} INFO - Started process 1219 to run task
[2023-12-24T17:06:49.679+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'read_s3_data', 'read_s3_data', 'scheduled__2022-10-20T00:00:00+00:00', '--job-id', '233', '--raw', '--subdir', 'DAGS_FOLDER/read.py', '--cfg-path', '/tmp/tmpf9ccy79y']
[2023-12-24T17:06:49.690+0000] {standard_task_runner.py:85} INFO - Job 233: Subtask read_s3_data
[2023-12-24T17:06:49.942+0000] {task_command.py:415} INFO - Running <TaskInstance: read_s3_data.read_s3_data scheduled__2022-10-20T00:00:00+00:00 [running]> on host 37dc6044b459
[2023-12-24T17:06:50.235+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='read_s3_data' AIRFLOW_CTX_TASK_ID='read_s3_data' AIRFLOW_CTX_EXECUTION_DATE='2022-10-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-10-20T00:00:00+00:00'
