[2023-04-19T12:45:26.882+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: age_check.age_check scheduled__2022-12-19T00:00:00+00:00 [queued]>
[2023-04-19T12:45:26.890+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: age_check.age_check scheduled__2022-12-19T00:00:00+00:00 [queued]>
[2023-04-19T12:45:26.891+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-04-19T12:45:26.892+0000] {taskinstance.py:1280} INFO - Starting attempt 4 of 4
[2023-04-19T12:45:26.892+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-04-19T12:45:26.900+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): age_check> on 2022-12-19 00:00:00+00:00
[2023-04-19T12:45:26.907+0000] {standard_task_runner.py:55} INFO - Started process 23666 to run task
[2023-04-19T12:45:26.910+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'age_check', 'age_check', 'scheduled__2022-12-19T00:00:00+00:00', '--job-id', '1487', '--raw', '--subdir', 'DAGS_FOLDER/age.py', '--cfg-path', '/tmp/tmpmcii5kb7']
[2023-04-19T12:45:26.912+0000] {standard_task_runner.py:83} INFO - Job 1487: Subtask age_check
[2023-04-19T12:45:26.968+0000] {task_command.py:388} INFO - Running <TaskInstance: age_check.age_check scheduled__2022-12-19T00:00:00+00:00 [running]> on host fe34f61acbb3
[2023-04-19T12:45:27.018+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=age_check
AIRFLOW_CTX_TASK_ID=age_check
AIRFLOW_CTX_EXECUTION_DATE=2022-12-19T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-19T00:00:00+00:00
[2023-04-19T12:45:27.027+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/age.py", line 35, in age_check
    birth_year = int(Variable.get('birth_year'))
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable birth_year does not exist'
[2023-04-19T12:45:27.041+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=age_check, task_id=age_check, execution_date=20221219T000000, start_date=20230419T124526, end_date=20230419T124527
[2023-04-19T12:45:27.053+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 1487 for task age_check ('Variable birth_year does not exist'; 23666)
[2023-04-19T12:45:27.084+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-04-19T12:45:27.103+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-05-20T20:56:47.142+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: age_check.age_check scheduled__2022-12-19T00:00:00+00:00 [queued]>
[2023-05-20T20:56:47.148+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: age_check.age_check scheduled__2022-12-19T00:00:00+00:00 [queued]>
[2023-05-20T20:56:47.150+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-05-20T20:56:47.150+0000] {taskinstance.py:1280} INFO - Starting attempt 4 of 4
[2023-05-20T20:56:47.151+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-05-20T20:56:47.161+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): age_check> on 2022-12-19 00:00:00+00:00
[2023-05-20T20:56:47.165+0000] {standard_task_runner.py:55} INFO - Started process 382 to run task
[2023-05-20T20:56:47.168+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'age_check', 'age_check', 'scheduled__2022-12-19T00:00:00+00:00', '--job-id', '1039', '--raw', '--subdir', 'DAGS_FOLDER/age.py', '--cfg-path', '/tmp/tmp4q9yvwm8']
[2023-05-20T20:56:47.171+0000] {standard_task_runner.py:83} INFO - Job 1039: Subtask age_check
[2023-05-20T20:56:47.227+0000] {task_command.py:388} INFO - Running <TaskInstance: age_check.age_check scheduled__2022-12-19T00:00:00+00:00 [running]> on host 242f95e3e8a8
[2023-05-20T20:56:47.276+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=age_check
AIRFLOW_CTX_TASK_ID=age_check
AIRFLOW_CTX_EXECUTION_DATE=2022-12-19T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-19T00:00:00+00:00
[2023-05-20T20:56:47.285+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/age.py", line 35, in age_check
    birth_year = int(Variable.get('birth_year'))
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable birth_year does not exist'
[2023-05-20T20:56:47.297+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=age_check, task_id=age_check, execution_date=20221219T000000, start_date=20230520T205647, end_date=20230520T205647
[2023-05-20T20:56:47.305+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 1039 for task age_check ('Variable birth_year does not exist'; 382)
[2023-05-20T20:56:47.344+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-05-20T20:56:47.363+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
