[2023-04-19T12:36:13.449+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: age_check.age_check scheduled__2022-07-31T00:00:00+00:00 [queued]>
[2023-04-19T12:36:13.459+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: age_check.age_check scheduled__2022-07-31T00:00:00+00:00 [queued]>
[2023-04-19T12:36:13.460+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-04-19T12:36:13.461+0000] {taskinstance.py:1280} INFO - Starting attempt 3 of 4
[2023-04-19T12:36:13.462+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-04-19T12:36:13.472+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): age_check> on 2022-07-31 00:00:00+00:00
[2023-04-19T12:36:13.480+0000] {standard_task_runner.py:55} INFO - Started process 21278 to run task
[2023-04-19T12:36:13.483+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'age_check', 'age_check', 'scheduled__2022-07-31T00:00:00+00:00', '--job-id', '519', '--raw', '--subdir', 'DAGS_FOLDER/age.py', '--cfg-path', '/tmp/tmpper37zyp']
[2023-04-19T12:36:13.485+0000] {standard_task_runner.py:83} INFO - Job 519: Subtask age_check
[2023-04-19T12:36:13.535+0000] {task_command.py:388} INFO - Running <TaskInstance: age_check.age_check scheduled__2022-07-31T00:00:00+00:00 [running]> on host fe34f61acbb3
[2023-04-19T12:36:13.592+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=age_check
AIRFLOW_CTX_TASK_ID=age_check
AIRFLOW_CTX_EXECUTION_DATE=2022-07-31T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-31T00:00:00+00:00
[2023-04-19T12:36:13.600+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/age.py", line 35, in age_check
    birth_year = int(Variable.get('birth_year'))
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable birth_year does not exist'
[2023-04-19T12:36:13.640+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=age_check, task_id=age_check, execution_date=20220731T000000, start_date=20230419T123613, end_date=20230419T123613
[2023-04-19T12:36:13.650+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 519 for task age_check ('Variable birth_year does not exist'; 21278)
[2023-04-19T12:36:13.696+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-04-19T12:36:13.716+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-05-17T09:52:02.249+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: age_check.age_check scheduled__2022-07-31T00:00:00+00:00 [queued]>
[2023-05-17T09:52:02.259+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: age_check.age_check scheduled__2022-07-31T00:00:00+00:00 [queued]>
[2023-05-17T09:52:02.260+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-05-17T09:52:02.261+0000] {taskinstance.py:1280} INFO - Starting attempt 3 of 4
[2023-05-17T09:52:02.262+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-05-17T09:52:02.280+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): age_check> on 2022-07-31 00:00:00+00:00
[2023-05-17T09:52:02.285+0000] {standard_task_runner.py:55} INFO - Started process 3971 to run task
[2023-05-17T09:52:02.293+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'age_check', 'age_check', 'scheduled__2022-07-31T00:00:00+00:00', '--job-id', '85', '--raw', '--subdir', 'DAGS_FOLDER/age.py', '--cfg-path', '/tmp/tmp8uxy1tna']
[2023-05-17T09:52:02.297+0000] {standard_task_runner.py:83} INFO - Job 85: Subtask age_check
[2023-05-17T09:52:02.415+0000] {task_command.py:388} INFO - Running <TaskInstance: age_check.age_check scheduled__2022-07-31T00:00:00+00:00 [running]> on host 242f95e3e8a8
[2023-05-17T09:52:02.502+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=age_check
AIRFLOW_CTX_TASK_ID=age_check
AIRFLOW_CTX_EXECUTION_DATE=2022-07-31T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-31T00:00:00+00:00
[2023-05-17T09:52:02.521+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/age.py", line 35, in age_check
    birth_year = int(Variable.get('birth_year'))
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable birth_year does not exist'
[2023-05-17T09:52:02.546+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=age_check, task_id=age_check, execution_date=20220731T000000, start_date=20230517T095202, end_date=20230517T095202
[2023-05-17T09:52:02.556+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 85 for task age_check ('Variable birth_year does not exist'; 3971)
[2023-05-17T09:52:02.584+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-05-17T09:52:02.620+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
